services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "pip install -r requirements-dev.txt &&
             alembic upgrade head &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
      - ./requirements-dev.txt:/app/requirements-dev.txt
      - ./requirements.txt:/app/requirements.txt
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
      - mongo
