services:
  # FastAPI Application Service
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount the source code directory for live-reloading
      - ./src:/app/src
    env_file:
      # Load environment variables from the .env file
      - ./.env
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - redis
      - mongo

  # PostgreSQL Database Service
  postgres:
    image: postgres:14-alpine
    volumes:
      # Persist database data across container restarts
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      # Load environment variables from the .env file
      - ./.env
    ports:
      - "5432:5432"

  # Redis Service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # MongoDB Database Service
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      # Persist mongodb data
      - mongo_data:/data/db
    env_file:
      # Load environment variables from the .env file
      - ./.env

volumes:
  # Define named volumes for data persistence
  postgres_data:
  mongo_data:
